services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest
    envVars:     
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: DB_TYPE
        value: "postgresdb"
      - key: DB_POSTGRESDB_HOST
        value: "ep-silent-silence-a1cardy0-pooler.ap-southeast-1.aws.neon.tech"  
      - key: DB_POSTGRESDB_DATABASE
        value: "neondb" 
      - key: DB_POSTGRESDB_USER
        value: "neondb_owner"
      - key: DB_POSTGRESDB_PASSWORD
        value: "npg_Rc3pHS0TqIzZ"
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_SSL_ENABLED
        value: true
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: true
        
      # Core n8n deployment/settings
      - key: N8N_PROTOCOL
        value: "https"
      - key: N8N_HOST
        value: "n8n-service-hb1l.onrender.com"
      - key: N8N_EDITOR_BASE_URL
        value: "https://n8n-service-hb1l.onrender.com/"
      - key: WEBHOOK_URL
        value: "https://n8n-service-hb1l.onrender.com/"
